export const CELL_COVERAGE_FINDER_LOADING = "CELL_COVERAGE_FINDER_LOADING";
export const CELL_COVERAGE_FINDER_CLOSED = "CELL_COVERAGE_FINDER_CLOSED";
export const CELL_COVERAGE_FINDER_PROMPTED = "CELL_COVERAGE_FINDER_PROMPTED";

export default {
  CELL_COVERAGE_FINDER_PROMPTED,
  CELL_COVERAGE_FINDER_CLOSED,
  CELL_COVERAGE_FINDER_LOADING
};
