export const REGISTER_MEMBERSHIP = "REGISTER_MEMBERSHIP";
export const REGISTER_MEMBERSHIP_SUCCESS = "REGISTER_MEMBERSHIP_SUCCESS";
export const REGISTER_MEMBERSHIP_ERROR = "REGISTER_MEMBERSHIP_ERROR";
