"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SET_CUSTOMER_INFO = exports.SET_CUSTOMER_INFO = "SET_CUSTOMER_INFO";

var SUBMIT_SUCCESS = exports.SUBMIT_SUCCESS = "SUBMIT_SUCCESS";

var SIGN_IN = exports.SIGN_IN = "SIGN_IN";
var SIGN_IN_SUCCESS = exports.SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
var SIGN_IN_ERROR = exports.SIGN_IN_ERROR = "SIGN_IN_ERROR";
var ACCOUNT_COMPROMISED = exports.ACCOUNT_COMPROMISED = "ACCOUNT_COMPROMISED";

var SIGN_UP = exports.SIGN_UP = "SIGN_UP";
var SIGN_UP_SUCCESS = exports.SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
var SIGN_UP_ERROR = exports.SIGN_UP_ERROR = "SIGN_UP_ERROR";

var REQUEST_PASSWORD_TOKEN = exports.REQUEST_PASSWORD_TOKEN = "REQUEST_PASSWORD_TOKEN";
var REQUEST_PASSWORD_TOKEN_COMPLETE = exports.REQUEST_PASSWORD_TOKEN_COMPLETE = "REQUEST_PASSWORD_TOKEN_COMPLETE";
var REQUEST_PASSWORD_TOKEN_SUCCESS = exports.REQUEST_PASSWORD_TOKEN_SUCCESS = "REQUEST_PASSWORD_TOKEN_SUCCESS";
var REQUEST_PASSWORD_TOKEN_ERROR = exports.REQUEST_PASSWORD_TOKEN_ERROR = "REQUEST_PASSWORD_TOKEN_ERROR";

var RESET_PASSWORD = exports.RESET_PASSWORD = "RESET_PASSWORD";
var RESET_PASSWORD_SUCCESS = exports.RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
var RESET_PASSWORD_ERROR = exports.RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

var REQUEST_SIGN_IN_WIDGET_STATE = exports.REQUEST_SIGN_IN_WIDGET_STATE = "REQUEST_SIGN_IN_WIDGET_STATE";

var FORM_FIELD_ERRORS = exports.FORM_FIELD_ERRORS = "FORM_FIELD_ERRORS";