"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var START_SIGN_IN = "START_SIGN_IN";
exports.START_SIGN_IN = START_SIGN_IN;
var START_SIGN_UP = "START_SIGN_UP";
exports.START_SIGN_UP = START_SIGN_UP;
var END_SIGN_IN = "END_SIGN_IN";
exports.END_SIGN_IN = END_SIGN_IN;
var END_SIGN_UP = "END_SIGN_UP";
exports.END_SIGN_UP = END_SIGN_UP;
var SIGN_IN = "SIGN_IN";
exports.SIGN_IN = SIGN_IN;
var SIGN_UP = "SIGN_UP";
exports.SIGN_UP = SIGN_UP;
var SET_SIGN_IN_ALERT = "SET_SIGN_IN_ALERT";
exports.SET_SIGN_IN_ALERT = SET_SIGN_IN_ALERT;
var SET_SIGN_UP_ALERT = "SET_SIGN_UP_ALERT";
exports.SET_SIGN_UP_ALERT = SET_SIGN_UP_ALERT;
var HANDLE_SIGN_IN_ERROR = "HANDLE_SIGN_IN_ERROR";
exports.HANDLE_SIGN_IN_ERROR = HANDLE_SIGN_IN_ERROR;
var HANDLE_SIGN_UP_ERROR = "HANDLE_SIGN_UP_ERROR";

exports.HANDLE_SIGN_UP_ERROR = HANDLE_SIGN_UP_ERROR;
var REQUEST_PASSWORD_TOKEN = "REQUEST_PASSWORD_TOKEN";
exports.REQUEST_PASSWORD_TOKEN = REQUEST_PASSWORD_TOKEN;
var REQUEST_PASSWORD_TOKEN_SUCCESS = "REQUEST_PASSWORD_TOKEN_SUCCESS";
exports.REQUEST_PASSWORD_TOKEN_SUCCESS = REQUEST_PASSWORD_TOKEN_SUCCESS;
var REQUEST_PASSWORD_TOKEN_ERROR = "REQUEST_PASSWORD_TOKEN_ERROR";

exports.REQUEST_PASSWORD_TOKEN_ERROR = REQUEST_PASSWORD_TOKEN_ERROR;
var RESET_PASSWORD = "RESET_PASSWORD";
exports.RESET_PASSWORD = RESET_PASSWORD;
var RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
exports.RESET_PASSWORD_SUCCESS = RESET_PASSWORD_SUCCESS;
var RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

exports.RESET_PASSWORD_ERROR = RESET_PASSWORD_ERROR;
var REQUEST_SIGN_IN_WIDGET_STATE = "REQUEST_SIGN_IN_WIDGET_STATE";
exports.REQUEST_SIGN_IN_WIDGET_STATE = REQUEST_SIGN_IN_WIDGET_STATE;