"use strict";

exports.__esModule = true;
var FORGOT_EMAIL = exports.FORGOT_EMAIL = "FORGOT_EMAIL";
var FORGOT_EMAIL_SUCCESS = exports.FORGOT_EMAIL_SUCCESS = "FORGOT_EMAIL_SUCCESS";
var FORGOT_EMAIL_ERROR = exports.FORGOT_EMAIL_ERROR = "FORGOT_EMAIL_ERROR";