export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const REQUEST_SIGN_IN_WIDGET_STATE = "REQUEST_SIGN_IN_WIDGET_STATE";
