"use strict";

exports.__esModule = true;
var GET_MODAL_INFO_SUCCESS = exports.GET_MODAL_INFO_SUCCESS = "GET_MODAL_INFO_SUCCESS";

var GET_SUBSCRIPTION_STATUS_REQUEST = exports.GET_SUBSCRIPTION_STATUS_REQUEST = "GET_SUBSCRIPTION_STATUS_REQUEST";
var GET_SUBSCRIPTION_STATUS_SUCCESS = exports.GET_SUBSCRIPTION_STATUS_SUCCESS = "GET_SUBSCRIPTION_STATUS_SUCCESS";
var GET_SUBSCRIPTION_STATUS_ERROR = exports.GET_SUBSCRIPTION_STATUS_ERROR = "GET_SUBSCRIPTION_STATUS_ERROR";

var UPDATE_AUTO_RENEW_REQUEST = exports.UPDATE_AUTO_RENEW_REQUEST = "UPDATE_AUTO_RENEW_REQUEST";
var UPDATE_AUTO_RENEW_SUCCESS = exports.UPDATE_AUTO_RENEW_SUCCESS = "UPDATE_AUTO_RENEW_SUCCESS";
var UPDATE_AUTO_RENEW_ERROR = exports.UPDATE_AUTO_RENEW_ERROR = "UPDATE_AUTO_RENEW_ERROR";

var UPDATE_PAYMENT_PREF_REQUEST = exports.UPDATE_PAYMENT_PREF_REQUEST = "UPDATE_PAYMENT_PREF_REQUEST";
var UPDATE_PAYMENT_PREF_SUCCESS = exports.UPDATE_PAYMENT_PREF_SUCCESS = "UPDATE_PAYMENT_PREF_SUCCESS";
var UPDATE_PAYMENT_PREF_ERROR = exports.UPDATE_PAYMENT_PREF_ERROR = "UPDATE_PAYMENT_PREF_ERROR";