export const START_SIGN_IN = "START_SIGN_IN";
export const START_SIGN_UP = "START_SIGN_UP";
export const END_SIGN_IN = "END_SIGN_IN";
export const END_SIGN_UP = "END_SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const SET_SIGN_IN_ALERT = "SET_SIGN_IN_ALERT";
export const SET_SIGN_UP_ALERT = "SET_SIGN_UP_ALERT";
export const HANDLE_SIGN_IN_ERROR = "HANDLE_SIGN_IN_ERROR";
export const HANDLE_SIGN_UP_ERROR = "HANDLE_SIGN_UP_ERROR";

export const REQUEST_PASSWORD_TOKEN = "REQUEST_PASSWORD_TOKEN";
export const REQUEST_PASSWORD_TOKEN_SUCCESS = "REQUEST_PASSWORD_TOKEN_SUCCESS";
export const REQUEST_PASSWORD_TOKEN_ERROR = "REQUEST_PASSWORD_TOKEN_ERROR";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const REQUEST_SIGN_IN_WIDGET_STATE = "REQUEST_SIGN_IN_WIDGET_STATE";
