export const ADDRESS_SELECT = "ADDRESS_SELECT";
export const ADDRESS_UNSELECT = "ADDRESS_UNSELECT";

export const ADDRESS_REQUEST_EDIT = "ADDRESS_REQUEST_EDIT";
export const ADDRESS_CANCEL_EDIT = "ADDRESS_CANCEL_EDIT";
export const ADDRESS_COMPLETE_EDIT = "ADDRESS_COMPLETE_EDIT";

export const ADDRESS_REQUEST_DELETE = "ADDRESS_REQUEST_DELETE";
export const ADDRESS_CANCEL_DELETE = "ADDRESS_CANCEL_DELETE";
export const ADDRESS_COMPLETE_DELETE = "ADDRESS_COMPLETE_DELETE";
export const ADDRESS_DELETE_CONFIRMED = "ADDRESS_DELETE_CONFIRMED";

export const ADDRESS_SET_ERROR = "ADDRESS_SET_ERROR";
export const ADDRESS_CLEAR_ERROR = "ADDRESS_CLEAR_ERROR";

export const ADDRESS_UPDATE = "ADDRESS_UPDATE";
export const ADDRESS_UPDATE_SUGGESTIONS = "ADDRESS_UPDATE_SUGGESTIONS";

export const ADDRESS_SEE_ALL_ADDRESSES = "ADDRESS_SEE_ALL_ADDRESSES";
export const ADDRESS_SET_LOADING = "ADDRESS_SET_LOADING";
export const ADDRESS_RETRIEVE_LOADING = "ADDRESS_RETRIEVE_LOADING";
export const UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR";
