"use strict";

exports.__esModule = true;
// todo auto generate
var GET_CREDIT_CARDS_REQUEST = exports.GET_CREDIT_CARDS_REQUEST = "GET_CREDIT_CARDS_REQUEST";
var GET_CREDIT_CARDS_SUCCESS = exports.GET_CREDIT_CARDS_SUCCESS = "GET_CREDIT_CARDS_SUCCESS";
var GET_CREDIT_CARDS_ERROR = exports.GET_CREDIT_CARDS_ERROR = "GET_CREDIT_CARDS_ERROR";
var CREATE_CREDIT_CARD_REQUEST = exports.CREATE_CREDIT_CARD_REQUEST = "CREATE_CREDIT_CARD_REQUEST";
var CREATE_CREDIT_CARD_SUCCESS = exports.CREATE_CREDIT_CARD_SUCCESS = "CREATE_CREDIT_CARD_SUCCESS";
var CREATE_CREDIT_CARD_ERROR = exports.CREATE_CREDIT_CARD_ERROR = "CREATE_CREDIT_CARD_ERROR";
var UPDATE_CREDIT_CARD_REQUEST = exports.UPDATE_CREDIT_CARD_REQUEST = "UPDATE_CREDIT_CARD_REQUEST";
var UPDATE_CREDIT_CARD_SUCCESS = exports.UPDATE_CREDIT_CARD_SUCCESS = "UPDATE_CREDIT_CARD_SUCCESS";
var UPDATE_CREDIT_CARD_ERROR = exports.UPDATE_CREDIT_CARD_ERROR = "UPDATE_CREDIT_CARD_ERROR";
var DELETE_CREDIT_CARD_MODE_CHANGE = exports.DELETE_CREDIT_CARD_MODE_CHANGE = "DELETE_CREDIT_CARD_MODE_CHANGE";
var DELETE_CREDIT_CARD_REQUEST = exports.DELETE_CREDIT_CARD_REQUEST = "DELETE_CREDIT_CARD_REQUEST";
var DELETE_CREDIT_CARD_SUCCESS = exports.DELETE_CREDIT_CARD_SUCCESS = "DELETE_CREDIT_CARD_SUCCESS";
var UPDATED_CREDIT_CARDS_AFTER_DELETE = exports.UPDATED_CREDIT_CARDS_AFTER_DELETE = "UPDATED_CREDIT_CARDS_AFTER_DELETE";
var DELETE_CREDIT_CARD_ERROR = exports.DELETE_CREDIT_CARD_ERROR = "DELETE_CREDIT_CARD_ERROR";
var REQUEST_EDIT_CREDIT_CARD = exports.REQUEST_EDIT_CREDIT_CARD = "REQUEST_EDIT_CREDIT_CARD";
var REQUEST_CLEAR_ERRORS = exports.REQUEST_CLEAR_ERRORS = "REQUEST_CLEAR_ERRORS";

var ADDRESS_VALIDATION_ERROR = exports.ADDRESS_VALIDATION_ERROR = "ADDRESS_VALIDATION_ERROR";
var SET_TRUNCATE = exports.SET_TRUNCATE = "SET_TRUNCATE";