"use strict";

exports.__esModule = true;
var INCREMENT_MSG_INDEX = exports.INCREMENT_MSG_INDEX = "INCREMENT_MSG_INDEX";

var HEADER_FETCH_STORES_REQUEST = exports.HEADER_FETCH_STORES_REQUEST = "HEADER_FETCH_STORES_REQUEST";
var HEADER_FETCH_STORES_SUCCESS = exports.HEADER_FETCH_STORES_SUCCESS = "HEADER_FETCH_STORES_SUCCESS";
var HEADER_FETCH_STORES_ERROR = exports.HEADER_FETCH_STORES_ERROR = "HEADER_FETCH_STORES_ERROR";

var RENDER_BIZ_TOOLS_MOBILE = exports.RENDER_BIZ_TOOLS_MOBILE = "RENDER_BIZ_TOOLS_MOBILE";
var INDEX_SUPER_DEPT_MOBILE = exports.INDEX_SUPER_DEPT_MOBILE = "INDEX_SUPER_DEPT_MOBILE";
var RENDER_DEPT_MOBILE = exports.RENDER_DEPT_MOBILE = "RENDER_DEPT_MOBILE";
var INDEX_DEPT_MOBILE = exports.INDEX_DEPT_MOBILE = "INDEX_DEPT_MOBILE";
var BTOOLS_INDEX_MOBILE = exports.BTOOLS_INDEX_MOBILE = "BTOOLS_INDEX_MOBILE";